measureSecond: 300
sop:
  practice:
    1:
      time_max: 300
      unit_minute_min: 0
      unit_minute_max: 45
      agent_sum: 4500
      type_sum: 1
      submit_max: 1000
      match_number: -1
    2:
      time_max: 300
      unit_minute_min: 0
      unit_minute_max: 45
      agent_sum: 4500
      type_sum: 3
      submit_max: 1000
      match_number: -1
  demo:
    1:
      time_max: 300
      unit_minute_min: 0
      unit_minute_max: 45
      agent_sum: 4500
      type_sum: 1
      submit_max: 1000
      match_number: 50
    2:
      time_max: 300
      unit_minute_min: 0
      unit_minute_max: 45
      agent_sum: 4500
      type_sum: 3
      submit_max: 1000
      endpoint: 85
  prod:
    1:
      time_max: 300
      unit_minute_min: 0
      unit_minute_max: 45
      agent_sum: 4660
      type_sum: 1
      submit_max: 1000
      endpoint: 51
    2:
      time_max: 300
      unit_minute_min: 0
      unit_minute_max: 45
      agent_sum: 4079
      type_sum: 3
      submit_max: 1000
      endpoint: 52


